spring:
  profiles:
    active:
      dev


  config:
    import: 'optional:file:.env[.properties]'

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    database: POSTGRESQL
    open-in-view: false
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true

  logging:
    level:
      epam:
        course:
          demo01: DEBUG
        org:
          hibernate:
            type:
              descriptor:
                sql:
                  BasicBinder: TRACE
            SQL: DEBUG
    file:
      path: ./logs
      name: ${logging.file.path}/log.log

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}


